spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ElielAlvesDB?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
